---
abstract: 'Minimalist Object Orientation (with Moose compatiblity)'
author:
  - 'mst - Matt S. Trout (cpan:MSTROUT) <mst@shadowcat.co.uk>'
build_requires:
  Test::Fatal: 0.003
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Moo
no_index:
  directory:
    - t
    - inc
requires:
  Class::Method::Modifiers: 1.07
  Module::Runtime: 0.013
  Role::Tiny: 1.0009
  strictures: 1.001001
version: 0.009_017
