---
abstract: 'Minimalist Object Orientation (with Moose compatibility)'
author:
  - 'mst - Matt S. Trout (cpan:MSTROUT) <mst@shadowcat.co.uk>'
build_requires:
  Test::Fatal: 0.003
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Moo
no_index:
  directory:
    - t
    - inc
    - xt
requires:
  Class::Method::Modifiers: 1.1
  Devel::GlobalDestruction: 0.11
  Module::Runtime: 0.012
  Role::Tiny: 1.002004
  strictures: 1.004003
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Moo
  license: http://dev.perl.org/licenses/
  repository: git://git.shadowcat.co.uk/gitmo/Moo.git
  x_IRC: irc://irc.perl.org/#moose
version: 1.002000
