--- #YAML:1.0
name:               Moo
version:            0.009006
abstract:           Minimalist Object Orientation (with Moose compatiblity)
author:
    - mst - Matt S. Trout (cpan:MSTROUT) <mst@shadowcat.co.uk>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::Fatal:  0.003
    Test::More:   0.96
requires:
    Class::Method::Modifiers:  1.05
    strictures:           1.001001
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
