---
abstract: 'Minimalist Object Orientation (with Moose compatibility)'
author:
  - 'mst - Matt S. Trout (cpan:MSTROUT) <mst@shadowcat.co.uk>'
build_requires:
  Test::Fatal: 0.003
  Test::More: 0.94
configure_requires:
  Dist::CheckConflicts: 0.02
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.82, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Moo
no_index:
  directory:
    - t
    - xt
requires:
  Class::Method::Modifiers: 1.1
  Devel::GlobalDestruction: 0.11
  Dist::CheckConflicts: 0.02
  Import::Into: 1.002
  Module::Runtime: 0.012
  Role::Tiny: 1.003002
  perl: 5.008001
  strictures: 1.004003
resources:
  IRC: irc://irc.perl.org/#moose
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Moo
  license: http://dev.perl.org/licenses/
  repository: https://github.com/moose/Moo.git
version: 1.004000
x_breaks:
  HTML::Restrict: 2.1.5
