#!/bin/sh

rm -rf fatlib

mkdir -p fatlib/Class/Method fatlib/Module fatlib/Role fatlib/Devel fatlib/Sub/Exporter

cp $(perldoc -l Class/Method/Modifiers.pm) fatlib/Class/Method/
cp $(perldoc -l Module/Runtime.pm) fatlib/Module/
cp $(perldoc -l Role/Tiny.pm) fatlib/Role/
cp $(perldoc -l strictures.pm) fatlib/
cp $(perldoc -l Devel/GlobalDestruction.pm) fatlib/Devel/
cp $(perldoc -l Sub/Exporter/Progressive.pm) fatlib/Sub/Exporter/

(fatpack file; echo '$ENV{PERL_STRICTURES_EXTRA} = 0;'; echo "1;") >FatMoo.pm

#rm -rf fatlib
